name: DeployDev10

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu

#      - run: ls
#      - run: mkdir "$HOME/.ssh"
#      - run: echo "${{ secrets.KEY }}" > "$HOME/.ssh/id_rsa"
#      - run: chmod 600 "$HOME/.ssh/id_rsa"
#      - run: echo Hello
#      - run: cd "$HOME"
#      - run: ls
#      - run: mkdir ".ssh"
#      - run: ls
#      - run: cd ".ssh"
#      - run: ls
      #- run: cat index.html
      #- run: echo "${{ secrets.KEY }}"
      #- run: cat "id_rsa"

      # Deploy
      - run: rsync -e "ssh -p 22 -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete . root@95.46.32.211:/home/lesson/web/lesson.it/public_html

# name: Deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v1

#     - name: Copy repository contents via scp
#       uses: appleboy/scp-action@master
#       env:
#         HOST: 95.46.32.211
#         USERNAME: root
#         PORT: 22
#         KEY: ${{ secrets.KEY }}
#       with:
#         source: "."
#         target: "/home/admin/web/dev4.ukeysecurity.com/public_html"

#     - name: Executing remote command
#       uses: appleboy/ssh-action@master
#       with:
#         host: 95.46.32.211
#         USERNAME: root
#         PORT: 22
#         KEY: ${{ secrets.KEY }}
#         script: ls
